[package]
name = "hera-zcash-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
futures-util = "0.3"
hera-types = { path = "../hera-types" }
hex = "0.4"
prost = "0.13"
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
zcash_client_backend = { version = "0.21.2", default-features = false, features = ["lightwalletd-tonic", "lightwalletd-tonic-transport", "orchard"] }
